project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Zhenyu Xu"
  search: true
  cookie-consent: false
  twitter-card: true
  open-graph: true
  site-url: https://zhenyu1029.github.io
  navbar:
    left:
      # - blog.qmd
      - text: "Resume"
        href: zhenyuxu_cv.pdf
    # right:
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
  # page-footer:
  #   left: "You can write somethig here too."

format:
  html:
    theme: cosmo
    css: styles.css
